# Site settings
title: shiping.liang
index_title: shiping # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: Two light
header-img: img/home-bg.jpg
email: icoool.ping@gmail.com
copyright_name: WhiteLight
description: "Online Territory of Shikher Verma"
baseurl: "/whiteLight" #base url is for when the site is not at the root but at some subdirectory.
url: http://liangsp.github.io/whiteLight #only used in disque comments for now
github_username:  shikherverma
facebook_username:  shikherverma1
email_username:  root@shikherverma.com
# used to estimate reading time
wpm: 180

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
#port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed]
